from modulos.usuarios import *
from modulos.categorias import *
from modulos.configuracoes import *
from modulos.posts import *
from modulos.login import *
from modulos.site import *
from modulos.dashboard import *
from modulos.api import *
from modulos.error import *
from modulos.tags import *
